[package]
name = "cpu-count"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[dependencies]
num_cpus = "1"
fasthash = "0.4.0"
base64 = "0.13.0"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]

[lib]
crate-type = ["cdylib"]
